ALTER TABLE `orders`
    MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'PACKING', 'READY_FOR_DELIVERY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `packedAt` DATETIME(3) NULL,
    ADD COLUMN `packedByUserId` INTEGER NULL,
    ADD COLUMN `stagingLabel` VARCHAR(100) NULL,
    ADD COLUMN `stagingZone` VARCHAR(100) NULL,
    ADD COLUMN `readyForDispatchAt` DATETIME(3) NULL;
