ALTER TABLE `order_items`
    ADD COLUMN `pickedQty` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `pickStatus` ENUM('PENDING', 'PICKED', 'PARTIAL', 'UNAVAILABLE', 'SUBSTITUTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `pickedAt` DATETIME(3) NULL,
    ADD COLUMN `pickedByUserId` INTEGER NULL,
    ADD COLUMN `scannedBarcode` VARCHAR(50) NULL,
    ADD COLUMN `pickIssueNote` VARCHAR(255) NULL;
